### PR TITLE
porting the tinyusb on MM32 MCU

### PR DESCRIPTION
**Pull request by zhangslice**
Signed-off-by: zhangslice <1304224508@qq.com>

**Describe the PR**
A clear and concise description of what this PR solve.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

### CODE REVIEW

**Comment by zhangslice** [comment]
porting the tinyusb on MM32 MCU

**Comment by zhangslice** [comment]
[mm327x_gcc.zip](https://github.com/hathach/tinyusb/files/6575198/mm327x_gcc.zip)
[tinyusb_keil.zip](https://github.com/hathach/tinyusb/files/6575199/tinyusb_keil.zip)

**Review by hathach — CHANGES_REQUESTED** [review]
Please do a proper PR with a minimal modification to add support for your MCUs and board only. You are removing supports for all other vendors. And please don't close/re-open the PR multiple times, I am fed up with notification by these actions.

**Comment by zhangslice** [comment]
OK, I'll modify it and upload it again






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hathach/tinyusb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 下午5:57
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hathach/tinyusb] porting the tinyusb on MM32 MCU (#867)





 
@hathach requested changes on this pull request.
 
Please do a proper PR with a minimal modification to add support for your MCUs and board only. And please don't close/re-open the PR multiple times.

**Comment by hathach** [comment]
This PR should be closed after #869 is merged. I think it is just better to add board support based on 869 instead of using this PR.

**Pull request closed without merging**
