### PR TITLE
RP2040 support

### PR DESCRIPTION
**Pull request by hathach**
**Describe the PR**
Add support for [Raspberry PI PICO RP2040](https://www.raspberrypi.org/products/raspberry-pi-pico/).

@kilograham You are probably too busy for other works at the moment. So I guess quickest way would be doing it myself, so that I could work on the ci-build (adding dependencies, fix build and test existing examples). 

Note: PR code can be found at https://github.com/raspberrypi/tinyusb/tree/pico , though since github doesn't allow to have PR between repo that aren't forks of each other. I need to fetch and push it as a branch of this repo.

### CODE REVIEW

**Comment by kilograham** [comment]
yeah go ahead - and i guess you are going to make the changes you suggested?

**Comment by hathach** [comment]
> yeah go ahead - and i guess you are going to make the changes you suggested?

yeah, I will try to do as best as I could for tweaking the port after fixing the ci with decent testing (may be in the form of follow up PR). Would you mind accepting the contributor invitation so that I could request your review on any changes related to rp2040 port in the long run.

**Comment by kilograham** [comment]
i think i already did accept

**Comment by hathach** [comment]
@kilograham I decide to do modification as follow-up and will merge this PR as it is even though it breaks the ci buidl. That will make it much easier for you to follow the changes and also pull the update.

**Pull request merged**
