### PR TITLE
samg implement dcd connect/disconnect

### PR DESCRIPTION
**Pull request by hathach**
implement part of #327

### CODE REVIEW

**Comment by pigrew** [comment]
@hathach 

Looks like this has the same concurrency issue.....   ```UDP_TXVC```  is also used by bus_reset().

**Comment by hathach** [comment]
Don't worry for this port. There won't be a bus reset while we doing disconnect/connect. There is also no usbkey guard like the msp430 to worry about

**Comment by pigrew** [comment]
Wow, that's tricky. Since the R-M-W cycle is in the ISR, I think it's safe.

**Comment by hathach** [comment]
> Wow, that's tricky. Since the R-M-W cycle is in the ISR, I think it's safe.

Not what I mean though, I mean there shouldn't a bus reset occurs anywhere near the execution of these function. But yeah, that helps as well.

**Pull request merged**
