### PR TITLE
Add Support stm32h5 for stm32h573i based on stm32_fsdev G0 implementa…

### PR DESCRIPTION
**Pull request by Lurcy38**
**Describe the PR**
Add Support stm32h5 for stm32h573i based on stm32_fsdev stm32g0 
Board supported : STM32H573I-DK
Implementation Tested on Windows with IAR and GCC toolchain ( via cubeide) and working properly 

**Additional context**
Tested only with audio examples, but sould be ok for other examples 
cmake patched : but not tested Linux build : not tested 
Added a temporary workaround in make file to support H5 HAL repo ( ARMCC_VERSION=0)

### CODE REVIEW

**Comment by Lurcy38** [comment]
i can send some boards if you need it, send me the adresse via the private email
regards

**Comment by HiFiPhile** [comment]
Nice PR ! I'm trying to push a commit to fix CI & typo but I got permission denied, could you give maintainers write permission or simply apply the patch ?

[0001-Fix-CI-typo.patch](https://github.com/hathach/tinyusb/files/13653428/0001-Fix-CI-typo.patch)

**Comment by Lurcy38** [comment]
done: you should have the access

**Comment by Lurcy38** [comment]
patch applied

**Review by hathach — COMMENTED** [review]
thank you for your PR. I have push some update to
- correct some cmake build
- rename board to stm32h573i_dk (dash does not play well with some build system)
- use linker script from st cmsis since it is available.
- add h5 to cmake ci build
- add h567nucleo since I have this board. Though usb isn't showed up yet. Probably due to clock setup (just copied from your dk just now), will fix in later push.

**Review by hathach — APPROVED** [review]
thank you for your PR, everything is working well now. The usb issue previously is due to h563 need 8Mhz clock out put from st-link onboard, while I tried to use my jlink. Will probably try to get it running without stlink later on.

**Pull request merged**
