### PR TITLE
Adjust line endings.

### LINKED ISSUE #187: Repository line endings normalization
While editing some files via the GitHub interface, I realized that this repository has inconsistent line endings.

For example, `src/host/usbh.h` has LF terminators while `src/device/usbd.c` has CRLF.

Do we want to make a big commit to normalize things to having LF in the repository?

I also suggest creating a `.gitattributes` file marking text files as text. Using LF seems to be what git is designed to do.

[dot_gitattributes.txt](https://github.com/hathach/tinyusb/files/3667553/dot_gitattributes.txt)

git does not have options to convert to CRLF when committing and to native when checking out files.

I'm happy to create a PR for this if it's something we want done.

### PR DESCRIPTION
**Pull request by pigrew**
Change CRLF-> LF
Also adds a gitattributes file, to force certain file extensions to be "text", and VisualStudio files to retain CRLF.

Closes #187 .

### CODE REVIEW

**Comment by pigrew** [comment]
(I really hope that I migrated things the correct direction...)

**Comment by pigrew** [comment]
@hathach 
I've updated this patch by merging in master.

**Comment by hathach** [comment]
thanks @pigrew , I will probably merge this after other pending issue, wouldn't want to cause any merge conflict with other PR (especially PR is developed on Windows machine)

**Comment by hathach** [comment]
Aahah.... Although I would love to merge this, but it is tons of conflict due to recent development now. I am sorry  it is too much of hassle for now, maybe we would do it later on. I feel so guilty :)

**Comment by pigrew** [comment]
@hathach It's not so difficult to recreate this. It'll take maybe 15 minutes to update the PR.

Should I update this PR, or should we wait longer?

**Comment by hathach** [comment]
@pigrew thank you very much, if you have time, please update it, I will do a merge right away. The master is a bit stable now without too many wip branches :)

**Comment by pigrew** [comment]
@hathach 

Was it really 42 files that need conversion, or am I doing it wrong now?

I believe that this is ready for merging.

**Comment by pigrew** [comment]
@hathach 

Updated again.

**Comment by kaysievers** [comment]
Yeah, phew ... :(

Why do you merge purely cosmetic PRs while there are still other PRs open, which will all fail now? Line endings can be converted with a one-liner, other PRs need to be manually rebased now.

This is for sure not a nice way to deal with actual contributions.

**Comment by hathach** [comment]
@kaysievers Yeah, you are right, it is not a nice way. but this PR has been postponed for quite some time for the same reason. I have to do manual merge for a couple of PR after this as well, But at least it is done now, one less thing to remember :). I could help with solving conflicts. I will try to be more careful later on :). Thanks for the comment

**Pull request merged**
