### PR TITLE
Add PlatformIO manifest

### PR DESCRIPTION
**Pull request by Yveaux**
Allows easy usage of TinyUSB in PlatformIO (see https://platformio.org/).

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
look good, please fix the missing end of file per ci recommendation.

**Comment by Yveaux** [comment]
Should be fixed. Thanks for the headsup!

**Review by hathach — APPROVED** [review]
look good, thank you

**Comment by nerdyscout** [comment]
hi @Yveaux 
I am trying to setup TinyUSB with platformio in [this project](https://github.com/nerdyscout/tinyusb_gettingstarted) but get 'undefined references' and can not figure out why. maybe you could help?

**Comment by Yveaux** [comment]
Hey @nerdyscout,

You should include the TinyUSB library as an external library instead of copying the files in your project.
The TinyUSB config file does need to be part of your project and CFG_TUSB_CONFIG_FILE must point at it; I placed it in include/tusb_config.h.

I use the TinyUSB library on an RPI Pico with Arduino, and the platformio.ini looks something like:

```
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

build_flags =
  -D DEBUG_PORT=Serial1
  -D DEBUG_BAUDRATE=115200
  -D DEBUG_RP2040_PORT=DEBUG_PORT
  -D PIO_FRAMEWORK_ARDUINO_NO_USB=1
  -D DISABLE_USB_SERIAL
  -D NO_USB
  -UUSE_TINYUSB
  ; TinyUSB settings
  -D CFG_TUSB_MCU=OPT_MCU_RP2040
  -D CFG_TUSB_OS=OPT_OS_PICO
  -D CFG_TUSB_RHPORT0_MODE=OPT_MODE_HOST
  -D CFG_TUSB_CONFIG_FILE=\"$PROJECT_DIR/include/tusb_config.h\"
  ; Log level: 1=Error, 2=Warning, 3=Info
  -D CFG_TUSB_DEBUG=2

lib_deps =
  https://github.com/hathach/tinyusb.git
```

Good luck!

**Comment by nerdyscout** [comment]
thank you @Yveaux !
I did add TinyUSB to the library as it should allow to use its hardware abstraction.
Using it as an external library now i run into exactly this issue ``bsp/*`` not been build as it is neither part of my project nor part of TinyUSB/src.  

````
#include "bsp/board_api.h" // can not be found from within my project, therefor init fails
#include "tusb.h"

//------------- prototypes -------------//
static void cdc_task(void);

/*------------- MAIN -------------*/
int main(void)
{
  board_init();

  // init device stack on configured roothub port
  tud_init(BOARD_TUD_RHPORT);

  if (board_init_after_tusb) {
    board_init_after_tusb();
  }

  while (1)
  {
    tud_task(); // tinyusb device task
    cdc_task();
  }
}
````

**Comment by Burke111-DEV** [comment]
> thank you @Yveaux ! I did add TinyUSB not as library as it should allow to use its hardware abstraction. Using it as an external library now i run into exactly this issue `bsp/*` not been build as it is neither part of my project nor part of TinyUSB/src.
> 
> ```
> #include "bsp/board_api.h" // can not be found from within my project, therefor board_init() not available which means board is not set up. 
> #include "tusb.h"
> 
> //------------- prototypes -------------//
> static void cdc_task(void);
> 
> /*------------- MAIN -------------*/
> int main(void)
> {
>   board_init();
> 
>   // init device stack on configured roothub port
>   tud_init(BOARD_TUD_RHPORT);
> 
>   if (board_init_after_tusb) {
>     board_init_after_tusb();
>   }
> 
>   while (1)
>   {
>     tud_task(); // tinyusb device task
>     cdc_task();
>   }
> }
> ```

I'm experiencing the same issue.
@Yveaux Please could you offer advice?
Kind regards

**Pull request merged**
