### PR TITLE
add tlsr dcd driver

### PR DESCRIPTION
**Pull request by tyustli**
**Describe the PR**
add tlsr dcd driver enum is ok.

### CODE REVIEW

**Comment by tyustli** [comment]
@HiFiPhile  can you review this PR?

**Comment by HiFiPhile** [comment]
Thanks for your PR, I can do coding check, but since I don't have the board I can't test if it works correctly.

**Comment by hathach** [comment]
@tyustli thank you for your PR, could you please provide a bit info on the board you are tested with e.g link to the board. I will try to see if it could got one to test with.

**Comment by tyustli** [comment]
This PR  is a simple implementation that only adapts enumerations

The link below is the official website

http://wiki.telink-semi.cn/wiki/chip-series/TLSR922x-Series/

**Comment by hathach** [comment]
thanks for the link, I couldn't find any board with the chip, seems like it is not very popular. Not sure how to get one for testing.

**Comment by tyustli** [comment]
https://m.tb.cn/h.5zq2uyd?tk=4xooWq8QVfU

**Pull request closed without merging**
