### PR TITLE
net_lwip_webserver example fix and improvement

### PR DESCRIPTION
**Pull request by HiFiPhile**
**Describe the PR**
- service_traffic: Don't call pbuf_free when ethernet_input is Ok
- Add MSOS 2.0 descriptor to auto load NCM driver on Windows 10.

### CODE REVIEW

**Comment by Slion** [comment]
What's the benefit of the NCM changes? I'm currently using NCM on Windows and it's been working fine.

**Comment by HiFiPhile** [comment]
> What's the benefit of the NCM changes? I'm currently using NCM on Windows and it's been working fine.

On Windows 10 you have to manually install NCM driver from device manager.

**Comment by Slion** [comment]
> On Windows 10 you have to manually install NCM driver from device manager.

I see, I only used it on Windows 11 so far and I did not need to install drivers.

**Comment by Slion** [comment]
We may want to add comments in code to explain that?

**Review by hathach — APPROVED** [review]
perfect PR as usual. Thank you very much

**Pull request merged**
