### PR TITLE
Update some settings for rx65n board

### PR DESCRIPTION
**Pull request by kkitayam**
**Describe the PR**
Update some settings to run examples.  I confirmed board_test and msc_cdc example work fine.

**Additional context**
I tested the patch on [RX65N-Target-Board](https://www.renesas.com/jp/en/products/microcontrollers-microprocessors/rx-32-bit-performance-efficiency-mcus/rx-family-target-board-target-board-rx-family). The board is the same as main board of [RX65N-Cloud-Kit](https://www.renesas.com/us/en/products/microcontrollers-microprocessors/rx-32-bit-performance-efficiency-mcus/rx65n-cloud-kit-renesas-rx65n-cloud-kit), I think the patch works on the kit.

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
Superb!! Thank you very much, will test this out today

**Comment by kkitayam** [comment]
I added a commit for `flash`. At first I only checked it with JLink.
`rpi-cli` sometimes report the following error, but after a few tries it succeeds.
```
[Error] E3000201: Cannot find the specified tool.
```

Just a reminder, after programming, the RX65N reset will not be released unless EJ2 is shorted.

**Review by hathach — APPROVED** [review]
superb !! Thank you very much. All the examples seems to work great on rx65n board including cdc_msc, hid_composite, net_lwip, midi_test. 

PS: There is CI issue, but it is due to the submodule is not updated, will do when making pr to master.

**Comment by hathach** [comment]
> I added a commit for `flash`. At first I only checked it with JLink.
> `rpi-cli` sometimes report the following error, but after a few tries it succeeds.
> 
> ```
> [Error] E4000004: A framing error occurred while receiving data. (BFW: 0354)
> ```
> 
> Just a reminder, after programming, the RX65N reset will not be released unless EJ2 is shorted.

Yeah, thank, `rpi-cli` does has issue but not very often. It requires me to manually insert header to enter debug mode when flashing, then remove it when running though. I much prefer jlink, btw, how would you add jlink to the rx65n target board. I may need it when doing doing more extensive work. It is not very clear in the board user manual.

**Comment by kkitayam** [comment]
> I much prefer jlink, btw, how would you add jlink to the rx65n target board. I may need it when doing doing more extensive work. It is not very clear in the board user manual.

@hathach 
Yeah, the board user manual has no information regarding JLink. But, since both JLink and RX family are compatible with the JTAG standard, we can refer the pin connections regarding JTAG.

I have checked JTAG connections for schematics and [JLink connector](https://www.segger.com/products/debug-probes/j-link/technology/interface-description). The result is shown below.

| Function  | RX65N pin| main board | option board | JLink connector |
|:---------:|:----------:|:----------:|:------------:|:---------------:|
| 3V3       | VCC        |   J1-14    | CN5-6        |    1            |
|TRST       | P34        |   J1-16    | CN5-7        |    3            |
|GND        | VSS        |   J1-12    | CN5-5        |    4            |
|TDI        | P30        |   J1-20    | CN5-10       |    5            |
|TMS        | P31        |   J1-19    | USER_SW      |    7            |
|TCK/FINEC  | P27        |   J1-21    | N/A          |    9            |
|TDO        | P26        |   J1-22    | CN5-9        |   13            |
|nRES       | RES#       |   J1-10    | RESET_SW     |   15            |

Note: To enable JTAG, RX65N requires following connections on main board.
- short EJ2 jumper header, to disable onboard E2L.
- short EMLE(J1-2) and 3V3(J1-14 or J2-10), to enable In-Circuit Emulator.

Unfortunately, the option board of RX65N-Cloud-Kit connects JTAG pins to some switches or floating. To use JLink with the option board, I think some modifications will be necessary.

I have attached a picture of my environment for your reference. I tested with JLink software V6.98c on Windows 10.
jlink

**Comment by hathach** [comment]
@kkitayam superb !! thank you very much again, this is really useful information. I totally need this for later working with it.Thank you again. Your board to be the same to my rx65n target board (part of the cloud kit). I think it is better to just name it rx65n target board instead of cloud kit, since more people will have the target board. 

Note: reason I order more expensive cloud kit because it has the daughter board with USB connector, since I have no idea if a simple jumper to usb breakout could work. Thank very much for the picture, it tell a lot !!!

**Pull request merged**
