### PR TITLE
Enhance EHCI

### LINKED ISSUE #2166: EHCI QHD reuses QTD on wrong endpoint
### Operating System

Linux

### Board

iMX RT 1060 evk with usb drive

### Firmware

On this branch: https://github.com/tannewt/circuitpython/tree/three_small

CP code.py is:
```python
import usb.core
import storage
import struct
import time

device = None
while device is None:
    print("searching for devices")
    for device in usb.core.find(find_all=True):
        print("pid", hex(device.idProduct))
        print("vid", hex(device.idVendor))
        print("man", device.manufacturer)
        print("product", device.product)
        print("serial", device.serial_number)
        break
    if not device:
        time.sleep(5)

# USB defines
DIR_SHIFT = 7
DIR_OUT = 0 << DIR_SHIFT
DIR_IN = 1 << DIR_SHIFT

# No shift
REQ_RCPT_DEVICE = 0
REQ_RCPT_INTERFACE = 1
REQ_RCPT_ENDPOINT = 2
REQ_RCPT_OTHER = 3


REQ_TYPE_SHIFT = 5
REQ_TYPE_STANDARD = 0 << REQ_TYPE_SHIFT
REQ_TYPE_CLASS = 1 << REQ_TYPE_SHIFT
REQ_TYPE_VENDOR = 2 << REQ_TYPE_SHIFT
REQ_TYPE_INVALID = 3 << REQ_TYPE_SHIFT

REQ_GET_DESCRIPTOR = 6
REQ_SET_INTERFACE = 11

DESC_DEVICE = 0x01
DESC_CONFIGURATION = 0x02
DESC_STRING = 0x03
DESC_INTERFACE = 0x04
DESC_ENDPOINT = 0x05

# IOCTL values
CTRL_SYNC          = 0   # Complete pending write process (needed at FF_FS_READONLY == 0)
GET_SECTOR_COUNT   = 1   # Get media size (needed at FF_USE_MKFS == 1)
GET_SECTOR_SIZE    = 2   # Get sector size (needed at FF_MAX_SS != FF_MIN_SS)
GET_BLOCK_SIZE     = 3   # Get erase block size (needed at FF_USE_MKFS == 1)
CTRL_TRIM          = 4   # Inform device that the data on the block of sectors is no longer used (needed at FF_USE_TRIM == 1)
IOCTL_INIT         = 5
IOCTL_STATUS       = 6

# SCSI commands
SCSI_CMD_TEST_UNIT_READY              = 0x00 # The SCSI Test Unit Ready command is used to determine if a device is ready to transfer data (read/write), i.e. if a disk has spun up, if a tape is loaded and ready etc. The device does not perform a self-test operation.
SCSI_CMD_INQUIRY                      = 0x12 # The SCSI Inquiry command is used to obtain basic information from a target device.
SCSI_CMD_MODE_SELECT_6                = 0x15 #  provides a means for the application client to specify medium, logical unit, or peripheral device parameters to the device server. Device servers that implement the MODE SELECT(6) command shall also implement the MODE SENSE(6) command. Application clients should issue MODE SENSE(6) prior to each MODE SELECT(6) to determine supported mode pages, page lengths, and other parameters.
SCSI_CMD_MODE_SENSE_6                 = 0x1A # provides a means for a device server to report parameters to an application client. It is a complementary command to the MODE SELECT(6) command. Device servers that implement the MODE SENSE(6) command shall also implement the MODE SELECT(6) command.
SCSI_CMD_START_STOP_UNIT              = 0x1B
SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL = 0x1E
SCSI_CMD_READ_CAPACITY_10             = 0x25 # The SCSI Read Capacity command is used to obtain data capacity information from a target device.
SCSI_CMD_REQUEST_SENSE                = 0x03 # The SCSI Request Sense command is part of the SCSI computer protocol standard. This command is used to obtain sense data -- status/error information -- from a target device.
SCSI_CMD_READ_FORMAT_CAPACITY         = 0x23 # The command allows the Host to request a list of the possible format capacities for an installed writable media. This command also has the capability to report the writable capacity for a media when it is installed
SCSI_CMD_READ_10                      = 0x28 # The READ (10) command requests that the device server read the specified logical block(s) and transfer them to the data-in buffer.
SCSI_CMD_WRITE_10                     = 0x2A # The WRITE (10) command requests that the device server transfer the specified logical block(s) from the data-out buffer and write them.

def get_descriptor(device, desc_type, index, buf, language_id=0):
    wValue = desc_type << 8 | index
    wIndex = language_id
    device.ctrl_transfer(REQ_RCPT_DEVICE | REQ_TYPE_STANDARD | DIR_IN, REQ_GET_DESCRIPTOR, wValue, wIndex, buf)

def get_device_descriptor(device):
    buf = bytearray(1)
    get_descriptor(device, DESC_DEVICE, 0, buf)
    full_buf = bytearray(buf[0])
    get_descriptor(device, DESC_DEVICE, 0, full_buf)
    return full_buf

def get_configuration_descriptor(device, index):
    buf = bytearray(4)
    get_descriptor(device, DESC_CONFIGURATION, index, buf)
    print(buf)
    wTotalLength = struct.unpack("<xxH", buf)[0]
    full_buf = bytearray(wTotalLength)
    get_descriptor(device, DESC_CONFIGURATION, index, full_buf)
    return full_buf

class USBMassStorage:
    def __init__(self, device: usb.core.Device, lun=0):
        print(get_device_descriptor(device))
        config_descriptor = get_configuration_descriptor(device, 0)

        self.in_ep = 0
        self.out_ep = 0

        self.sector_count = None
        # Look over each descriptor for mass storage interface and then the two
        # endpoints.
        in_msc_interface = False
        i = 0
        while i < len(config_descriptor):
            descriptor_len = config_descriptor[i]
            descriptor_type = config_descriptor[i + 1]
            print(descriptor_len, descriptor_type)
            if descriptor_type == DESC_INTERFACE:
                interface_number = config_descriptor[i + 2]
                interface_class = config_descriptor[i + 5]
                interface_subclass = config_descriptor[i + 6]
                in_msc_interface = interface_class == 8 and interface_subclass == 6
                print("interface", interface_number, interface_class, interface_subclass)
            elif descriptor_type == DESC_ENDPOINT and in_msc_interface:
                endpoint_address = config_descriptor[i + 2]
                if endpoint_address & DIR_IN:
                    self.in_ep = endpoint_address
                else:
                    self.out_ep = endpoint_address
                print(f"endpoint {endpoint_address:02x}")
            i += descriptor_len

        if self.in_ep == 0 or self.out_ep == 0:
            raise ValueError("No MSC interface found")

        # TODO: Get the max lun.
        self.lun = lun
        self.device = device
        self.device.set_configuration(0)

        self.cbw = bytearray(31)
        self.cbw[0:4] = b"\x55\x53\x42\x43"
        self.cbw[14] = self.lun
        self.csw = bytearray(13)
        self.csw[0:4] = b"\x55\x53\x42\x53"

        print("wait for ready")
        self._wait_for_ready(tries=5)

    def _scsi_command(self, direction, command, data) -> None:
        struct.pack_into("<IBxB", self.cbw, 8, len(data), direction, len(command))
        self.cbw[16:16+len(command)] = command
        # Write out the command.
        print("cbw", self.cbw)
        self.device.write(self.out_ep, self.cbw)
        # Depending on the direction, read or write the data.
        if data:
            if direction == DIR_IN:
                self.device.read(self.in_ep, data)
            else:
                self.device.write(self.out_ep, data)

        # Get the status.
        self.device.read(self.in_ep, self.csw)
        print("csw", self.csw)

    def _wait_for_ready(self, tries=100):
        status = 12
        self.csw[status] = 1
        test_ready = bytearray(6)
        test_ready[0] = SCSI_CMD_TEST_UNIT_READY
        test_ready[1] = self.lun

        sense_response = bytearray(18)
        sense = bytearray(6)
        sense[0] = SCSI_CMD_MODE_SENSE_6
        sense[4] = len(sense_response)
        try_num = 0
        self._scsi_command(DIR_OUT, test_ready, b"")
        while self.csw[status] != 0 and try_num < tries:
            try_num += 1
            self._scsi_command(DIR_IN, sense, sense_response)
            self._scsi_command(DIR_OUT, test_ready, b"")

    def _inquire(self) -> None:
        response = bytearray(36)
        command = bytearray(6)
        command[0] = SCSI_CMD_INQUIRY
        command[4] = len(response)
        self._scsi_command(DIR_IN, command, response)
        print(response)

    def _read_capacity(self) -> None:
        command = bytearray(10)
        command[0] = SCSI_CMD_READ_CAPACITY_10
        response = bytearray(8)

        self._scsi_command(DIR_IN, command, response)

        self.sector_count, self.block_size = struct.unpack(">II", response)
        self.sector_count += 1 # Response has the last valid number. Count is one greater.

    def readblocks(self, block_num: int, buf: bytearray) -> None:
        print("read", block_num, buf)

    def writeblocks(self, block_num: int, buf: bytearray) -> None:
        print("write", block_num, buf)

    def ioctl(self, operation: int, arg: Optional[int] = None) -> Optional[int]:
        if operation == GET_SECTOR_COUNT:
            print("get sector count")
            if not self.sector_count:
                self._read_capacity()
            return self.sector_count
        print("ioctl", operation, arg)

print("mounting")
msc = USBMassStorage(device)
vfs = storage.VfsFat(msc)

```

### What happened ?

Assert hit:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x6002c5d2 in tuh_task_ext (in_isr=in_isr@entry=false, timeout_ms=4294967295) at ../../lib/tinyusb/src/host/usbh.c:506
506                     TU_ASSERT(false, );
(gdb) bt
#0  0x6002c5d2 in tuh_task_ext (in_isr=in_isr@entry=false, timeout_ms=4294967295) at ../../lib/tinyusb/src/host/usbh.c:506
#1  0x6002c5ee in tuh_task_ext (timeout_ms=timeout_ms@entry=4294967295, in_isr=in_isr@entry=false) at ../../lib/tinyusb/src/host/usbh.c:401
#2  0x60028b3e in tuh_task () at ../../lib/tinyusb/src/host/usbh.h:125
#3  usb_background () at ../../supervisor/shared/usb/usb.c:206
#4  0x00002796 in background_callback_run_all () at ../../supervisor/shared/background_callback.c:102
#5  0x600506de in _xfer (timeout=0, xfer=0x20007b08) at ../../shared-module/usb/core/Device.c:155
#6  common_hal_usb_core_device_write (self=0x2020ba60, endpoint=<optimized out>, buffer=0x2020c1c0 "&h", len=13, timeout=0) at ../../shared-module/usb/core/Device.c:230
#7  0x600413e6 in usb_core_device_read (n_args=<optimized out>, pos_args=<optimized out>, kw_args=<optimized out>) at ../../shared-bindings/usb/core/Device.c:203
```

### How to reproduce ?

Run the code.py on a CP debug build from that branch with a mass storage device plugged in.

### Debug Log as txt file (LOG/CFG_TUSB_DEBUG=2)

```
ehci xfer to 02 on 1
  qhd 0x202013c0 qtd 0x20201c40
  ehci xfer error 02 on 1 result 1
  qhd 0x202013c0 qtd 0x20201c40 current 0x20201c40
  cb done dev 1 ep 02 on 0x60050419
   res 1 len 0
xfer dev 1 ep 81 to 0x60050419
ehci xfer to 81 on 1
  qhd 0x20201400 qtd 0x20201c40
  ehci xfer error 81 on 1 result 1
  qhd 0x20201400 qtd 0x20201c40 current 0x20201c40
  ehci xfer error 82 on 1 result 1
  qhd 0x202013c0 qtd 0x20201c40 current 0x20201c40
  cb done dev 1 ep 81 on 0x60050419
   res 1 len 0
  cb done dev 1 ep 82 on 0x0
   res 1 len 0
```

This is my own printf debugging. The second to last line shows that the done cb is NULL for ep 82, which I never initiated ("ehci xfer to"). This is right after an error on the correct endpoint. Both qhd's have the same qtd set as current. So, I suspect we aren't completely detaching a qtd from the qhd before reusing it.

Full log with tinyusb logging on too:
[imx1060_tinyusb_log.txt](https://github.com/hathach/tinyusb/files/12135227/imx1060_tinyusb_log.txt)

### Screenshots

_No response_

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

### PR DESCRIPTION
**Pull request by hathach**
**Describe the PR**
- Fix issue with hub status_change is not aligned
- EHCI use standard USB complete interrupt instead of custom chipidea async/period interrupt to be more compatible with other ehci implementation
- refactor usb complete & error isr processing, merge, update. Should probably fix #2166 . @tannewt please try it out when you have time.

### CODE REVIEW

**Comment by tannewt** [comment]
I think this is needed to write the detach values back to RAM:

```c
// Remove an attached TD from queue head
static void qhd_remove_qtd(ehci_qhd_t *qhd) {
  ehci_qtd_t * volatile qtd = qhd->attached_qtd;

  qhd->attached_qtd = NULL;
  qhd->attached_buffer = 0;
  hcd_dcache_clean(qhd, sizeof(ehci_qhd_t));

  qtd->used = 0; // free QTD
  hcd_dcache_clean(qtd, sizeof(ehci_qtd_t));
}
```

**Comment by hathach** [comment]
> I think this is needed to write the detach values back to RAM:

It may not be needed, since these are all software only field for managing driver accessed by CPU only. EHCI controller does know/need to access these values at all.

**Comment by tannewt** [comment]
> > I think this is needed to write the detach values back to RAM:
> 
> It may not be needed, since these are all software only field for managing driver accessed by CPU only. EHCI controller does know/need to access these values at all. Let me know ifthis PR help with your issue

They are software only *but* you invalidate the cache for QHD and QTD because there is data on the same cache line that the EHCI controller needs. That drops any values written to the cache but not RAM. So, you need to clean when writing QTD or QHD because you may invalidate it later.

**Comment by hathach** [comment]
Indeed, you are right, I am updating PR with suggested changes :)

**Pull request merged**
