### PR TITLE
lpc17xx move set configdevice into set address for removing dcd_set_config()

### PR DESCRIPTION
**Pull request by hathach**
This is technically not right, but it will have lpc17 behaves the same as other mcu vendor. Tested and works well on lpc4088 qs

### CODE REVIEW

**Comment by hathach** [comment]
@majbthrd if you could remove the use of `dcd_set_config()` in nuc505, I will remove the API altogether in this PR. We can then sync your PR #326 with this to continue our work there.

**Comment by hathach** [comment]
@majbthrd currently nuc505 only use set_config() to reset DToggle for endpoints. Maybe it can be achieved somewhere. Normally after setConfig is endpoint open, which already set DToggle to DATA0 already !!

**Comment by majbthrd** [comment]
> 
> 
> @majbthrd currently nuc505 only use set_config() to reset DToggle for endpoints. Maybe it can be achieved somewhere. Normally after setConfig is endpoint open, which already set DToggle to DATA0 already !!

I've added PR #347, which follows the same sort of approach that you did for lpc17xx.

**Comment by hathach** [comment]
> The existing dcd_set_config() call in ./device/usbd.c may disappear, but something eventually needs to replace that call in the future once SET_CONFIGURATION supports multiple configurations. IMHO, the replacement should disable all non-control endpoints (whether that is implemented as: a) a direct DCD API to perform this action, or b) some middleman/shim routine that uses another DCD API to exhaustively close all endpoints).
> 
> I'm personally partial to (a), but I can also see the upside of (b), since the same DCD API called in that situation might also benefit future classes with more elaborate alternate interfaces.

Yeah, the (b) dedicated close_all() is also very useful for some ports that are require a bit of buffer allocating based on packetsize like stm32 fsdev. It is essentially an bus_reset() without the actual hardware signal. We will see though, no rush into that, since there is no benefit yet :smiley:

**Pull request closed without merging**
