### PR TITLE
add support SAML21

### PR DESCRIPTION
**Pull request by sabas1080**
Hi @hathach 

I have added support SAML21 

depends on https://github.com/hathach/microchip_driver/pull/6

Thanks

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
The changes look great. Have you tried some of the stock examples to see if they work out, especially `cdc_msc` and `hid_composite`.

**Comment by sabas1080** [comment]
> The changes look great. Have you tried some of the stock examples to see if they work out, especially `cdc_msc` and `hid_composite`.

yes,  I tried cdc_msc, work ok

**Comment by hathach** [comment]
> > The changes look great. Have you tried some of the stock examples to see if they work out, especially `cdc_msc` and `hid_composite`.
> 
> yes, I tried cdc_msc, work ok

Great, thanks for confirmation. Can you add the SAML21 family into the ci build right before saml22.  https://github.com/hathach/tinyusb/blob/master/.github/workflows/build.yml#L52

I think you need to bump up the microchip submodule as well for CI to pass

**Comment by hathach** [comment]
I have fixed ci build, but couldn't push to your  fork to update PR. Could you give  me the write permission to your fork, so that we could wrap this PR.

**Comment by sabas1080** [comment]
> I have fixed ci build, but couldn't push to your fork to update PR. Could you give me the write permission to your fork, so that we could wrap this PR.

I have added as a contributor

**Review by hathach — APPROVED** [review]
Everything look great, thank you very much for your PR.

**Pull request merged**
