### PR TITLE
CDC : Add xfer_fifo & DMA support 

### PR DESCRIPTION
**Pull request by HiFiPhile**
**Describe the PR**
3rd part of #926

- Add xfer_fifo to CDC class like UAC2.
- Export tu_fifo_buffer_info_t for DMA support.

tud_cdc_rx_wanted_cb is WIP, it needs backward write pointer.

### CODE REVIEW

**Comment by dmberrycom** [comment]
Curious to understand if this DMA feature is likely to make it into the main branch ?

**Comment by hathach** [comment]
It kind of falling off my radar due to other pending works. I will revise this later on when having more time. There is no reason why we wouldn’t want this, just want to make sure the API is right.

**Comment by HiFiPhile** [comment]
> Expect dma capability in dwc2

@rrrrrrobot @diggit @donbommelon check #2576

**Comment by HiFiPhile** [comment]
Deperacted

**Pull request closed without merging**
