### PR TITLE
Minor style improvements found by cppcheck

### PR DESCRIPTION
**Pull request by dp111**
Minor style improvements found by cppcheck.

### CODE REVIEW

**Comment by HiFiPhile** [comment]
Thank you for the PR, but we are not interested for these variable name changing, for example `buffer` is used elsewhere.

**Comment by dp111** [comment]
Just so I know are you interested in the function prototypes matching the functions ? Would you like to cherry pick the break;  to be inside the #if  ?

**Comment by HiFiPhile** [comment]
> Just so I know are you interested in the function prototypes matching the functions ?

Could you elaborate, is there any mismatched prototype ?

> Would you like to cherry pick the break; to be inside the #if ?

Yes please.

**Comment by dp111** [comment]
In tusb_fifo.h we currently have : 
   bool tu_fifo_read(tu_fifo_t* f, void * p_buffer);
in tusb_fifo.c  :
   bool tu_fifo_read(tu_fifo_t* f, void * buffer)

This is super minor but the PR intended to made the second parameter match.

**Comment by HiFiPhile** [comment]
> In tusb_fifo.h we currently have :
bool tu_fifo_read(tu_fifo_t* f, void * p_buffer);
in tusb_fifo.c :
bool tu_fifo_read(tu_fifo_t* f, void * buffer)

Didn't notice that, please change the prototype to use `buffer` since it's more used.

Speaking of which the project doesn't have a naming convention yet...

**Pull request closed without merging**
