### PR TITLE
Add support for TI MSP-EXP432E401Y

### PR DESCRIPTION
**Pull request by kkitayam**
**Describe the PR**
Add support for [MSP-EXP432E401Y](https://www.ti.com/tool/MSP-EXP432E401Y) as a DCD.

This patch has no support for followings.
- Handling the dedicated DMA for USB
- Handling ULPI for high speed PHY

I have checked that following examples work with Windows 10.
- cdc_msc
- cdc_msc_freertos
- net_lwip_webserver
- uac2_headset
- video_capture

And I did the USB3CV test for CH.9, HID and MSC. CH.9 and HID passed, but MSC failed.

**Additional context**
This driver may lack generating CONTROL_STAGE_ACK for control read transfers.
The USB controller probably receives automatically a STATUS OUT packet as a ACK on control read transfers. So, the USB host may complete to send a STATUS OUT packet and complete to send the next setup packet before USBD invokes `dcd_edpt_xfer()` to be ready for receiving STATUS OUT packet. Therefore we have no way to generate CONTROL_STAGE_ACK precise on control read transfers.

#670 ek-tm4c123gxl probably has also the same IP. But, it may use difference configuration parameters or revision.

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
Brilliant work, indeed, this mentor graphic is used widely on most of TI arm mcu. A quick google show that other TI also use this
- Stellaris LM3S
- C2000
- TM4C (tiva C), the msp432E is actually a re-branded from tm4c-129x

I have an TM4c123x launchpad board and could help to test it out, give me a bit of time to get its bsp set up. Btw the core is called "USB 2.0 MULTI-POINT DUAL-ROLE CONTROLLER". Its Databook is actually downloadable online by googling **musbmhdrc_pspgUSB** (you shouldn't do this because it is confidential, you know what I mean :smile:  )

**Comment by hathach** [comment]
no worry about DMA, FIFO based actually can help to reduce the interim buffer from class driver e.g CDC. Although it is less idea on mcu with large SRAM, it give option to run it more efficiently on smaller mcu. I have an plan to drop class driver interim EP Buffer on supported DCD later on (selectable). 

For ULPI, not really an issue as well, those requires board with external PHY and the software setup/config is pretty straightforward from my exp with stm32h743. Those can wait :)

**Comment by kkitayam** [comment]
Thank you for your comments. After https://github.com/hathach/ti_driver/pull/4 is merged, I will update the submodule for TI driver and status to ready for review.

> FIFO based actually can help to reduce the interim buffer from class driver e.g CDC. Although it is less idea on mcu with large SRAM, it give option to run it more efficiently on smaller mcu. I have an plan to drop class driver interim EP Buffer on supported DCD later on (selectable).

Yeah, I agree and that's good. 

Actually, I didn't have boards with support for high speed, so I bought the board. But, I had not been know an optional board needed. 😞 After implement this patch, I have know it...

**Comment by hathach** [comment]
> Thank you for your comments. After hathach/ti_driver#4 is merged, I will update the submodule for TI driver and status to ready for review.

merged !!

> Actually, I didn't have boards with support for high speed, so I bought the board. But, I had not been know an optional board needed. disappointed After implement this patch, I have know it...

Yeah, I totally understand your feeling from my own experience. They didn't make it very clear from the feature page.

**Comment by kkitayam** [comment]
Thank you for merging. I have updated the submodule for TI driver.

**Comment by aspdigital** [comment]
I have an MSP432E board, and if I get a chance this week I will test the code on it.

**Comment by hathach** [comment]
> Thank you for your comments. I have no more changes regarding this PR. I am ready for merge!

Superb !! Thank you for the great pr. Merged now

> I have an MSP432E board, and if I get a chance this week I will test the code on it.

Looking forward to hear from your result. Please let us know if you find out any issues.

**Pull request merged**
