### PR TITLE
change dcd_dcache_*() API return type from void to bool

### PR DESCRIPTION
**Pull request by hathach**
This pull request includes multiple changes aimed at improving the handling of data cache (DCache) operations and configuration. The most important changes involve the introduction of new macros for host DCache declarations, changes to DCache-related function signatures, and the unification of DCache line size configurations.

### DCache Handling Improvements:
* [`src/common/tusb_types.h`](diffhunk://#diff-05c83118cd4f8865af0380b64c1a1c073534cfc3f19d3bce7caa4904641fb2b8R56-R74): Introduced new macros for host DCache declarations, including `TUH_EPBUF_DCACHE_SIZE`, `TUH_EPBUF_DEF`, and `TUH_EPBUF_TYPE_DEF`. These macros help in declaring endpoint buffers with appropriate DCache handling.
* [`src/device/dcd.h`](diffhunk://#diff-7a586eb0e925e422fb5b2559b14488d80d642150993a3c6393a389d72e737b4aL96-R104): Changed the return type of DCache-related functions (`dcd_dcache_clean`, `dcd_dcache_invalidate`, and `dcd_dcache_clean_invalidate`) from `void` to `bool` to indicate success or failure.
* `src/device/usbd.c`, `src/portable/chipidea/ci_hs/dcd_ci_hs.c`, `src/portable/synopsys/dwc2/dcd_dwc2.c`, `src/portable/synopsys/dwc2/dwc2_esp32.h`: Updated the implementations of DCache-related functions to return `bool` and use `TU_VERIFY` for validation. [[1]](diffhunk://#diff-547ff7242684ae3243ee7fa7a3fb7a6efc3f2d2bae3e4ba4908b281f47b871d4L100-R112) [[2]](diffhunk://#diff-d3de4a8155906454380668b2a1418835f37b7c1ce27f4d14f89be8e8abb9118fL37-L73) [[3]](diffhunk://#diff-1f2490fb8ceeb23801391e207e1972f09dd6a7fbbe431154211cc1896dc363a0L86-R98) [[4]](diffhunk://#diff-519cbf28ad89f0f97bad11702bf4b86d32d74ca95c21be25ffea5fa0de9c4866L133-R148)

### Configuration Simplification:
* [`src/common/tusb_mcu.h`](diffhunk://#diff-86e284bab4a7d1bd080414dc1b4ee867a959ff5e39c501c0899a8b35e5dc4a63R367-L379): Removed redundant DCache configuration macros and set default values for DCache enable flags.
* [`src/tusb_option.h`](diffhunk://#diff-055197dcf69fbff20e8e8364119495cef6e4a3a9be97fd39e02a29115eaa5302R400-R407): Unified the DCache line size configurations by defining `CFG_TUD_MEM_DCACHE_LINE_SIZE` and `CFG_TUH_MEM_DCACHE_LINE_SIZE` based on `CFG_TUSB_MEM_DCACHE_LINE_SIZE`. [[1]](diffhunk://#diff-055197dcf69fbff20e8e8364119495cef6e4a3a9be97fd39e02a29115eaa5302R400-R407) [[2]](diffhunk://#diff-055197dcf69fbff20e8e8364119495cef6e4a3a9be97fd39e02a29115eaa5302L436-R444) [[3]](diffhunk://#diff-055197dcf69fbff20e8e8364119495cef6e4a3a9be97fd39e02a29115eaa5302L559-R563)

### CODE REVIEW

**Comment by roma-jam** [comment]
@hathach 
Hi, do you have any plans to make a `v0.17.1` release soon?

**Comment by hathach** [comment]
> @hathach Hi, do you have any plans to make a `v0.17.1` release soon?

I currently have no plan, but if espressif want a tag version, I could probably release it in a week or two. I  will  need to review other pendings PRs and also wait for the audio driver to be updated to work with dcache as well.

**Comment by roma-jam** [comment]
Hi @hathach,

sorry for poking you in here, bus as we started the discussion, then: 

> I currently have no plan, but if espressif want a tag version, I could probably release it in a week or two.

Is there any news about tagging the version?

**Comment by hathach** [comment]
@roma-jam we can make a release after https://github.com/hathach/tinyusb/pull/2865 since that also include audio driver update for correct cache size line. I also need to update docs for release note as well. Give me a bit more time.

**Comment by roma-jam** [comment]
Hi @hathach , 

thanks for returning back to me. 
Sure, no worries, take you time and let me know if there is anything I can help with / verify smth.

**Pull request merged**
