### PR TITLE
Add fifo get function to CDC class for DMA transfer

### PR DESCRIPTION
**Pull request by HiFiPhile**
**Describe the PR**
Like audio class, CDC need DMA support in order to support high speed transfer.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

### CODE REVIEW

**Comment by HiFiPhile** [comment]
It's not enough to just export the fifo, need a mechanism to call `_prep_out_transaction`.

**Review by hathach — COMMENTED** [review]
I don't think exposing fifos is good idea. I don't have a specific suggestion for now, but we will need to spend more time to look at this later on.

**Comment by HiFiPhile** [comment]
In fact CDC streaming is needed by my company's project which restarted recently, following my tests last year.

For the short time expose the fifo fit my need, of cause we can make something better for example expose only fifo_info even add edpt_xfer_fifo support.

**Comment by hathach** [comment]
> In fact CDC streaming is needed by my company's project which restarted recently, following my tests last year.
> 
> For the short time expose the fifo fit my need, of cause we can make something better for example expose only fifo_info even add edpt_xfer_fifo support.

It is easy to expose an API, but it is very hard to drop one. I would prefer to figure it all out first. I think for now, you could make an "hack" for your fork e.g dropping static in the function/variable in the cdc_device and have extern in your app. It is not ideal, but I would be more flexible

**Comment by HiFiPhile** [comment]
I've opened a new issue to discuss #920 .

**Pull request closed without merging**
