### PR TITLE
Add CDC+UAC2 composite device example for Pico

### PR DESCRIPTION
**Pull request by kholia**
Purpose: This example provides a composite CDC + UAC2 device on top of a Raspberry Pi Pico board.

Closes: https://github.com/hathach/tinyusb/pull/1717

Motivation:

The CDC + UAC2 composite device happens to be important, especially in the amateur radio community.

Modern radios (`rigs`) like Icom IC-7300 + IC-705 expose a sound card and a serial device (`composite device`) to the computer over a single USB cable. This allows for Audio I/O and CAT control over a single USB cable which is very convenient. By including and maintaining this example in TinyUSB repository, we enable the amateur radio community to build (`homebrew`) radios with similar functionality as the (expensive) commercial rigs. This PR is important in bridging this specific gap between the commercial rigs and homebrew equipment.

https://digirig.net/digirig-mobile-rev-1-9/ is a digital interface for interfacing radios (that lack an inbuilt digital interface) with computers. Digirig Mobile works brilliantly (is OSS!) and is a big improvement over traditional digital interfaces (like the SignaLink USB Interface). By using a Raspberry Pi Pico powered CDC + UAC2 composite device, we can simplify the Digirig Mobile schematic, drastically reduce the manufacturing cost, and (again) enable the homebrewers community to  homebrew a modern digital interface with ease themselves.

Build Notes:

```
cd examples/device/cdc_uac2

export PICO_SDK_PATH=$HOME/pico-sdk

cmake -DFAMILY=rp2040 pico .

make BOARD=raspberry_pi_pico all
```

Testing Notes:

This example was tested successfully on a Raspberry Pi Pico board connected to the following USB hosts:

- An AMD64 laptop running Ubuntu 22.04 LTS OS.
- Android 12 / 13 phone
- Windows 10 running in VirtualBox

Known Issues:

Running `audacity` on Linux results in a crash (or hang) with the following present in `dmesg`:

```
[ 1674.259606] usb 1-1: 1:1: usb_set_interface failed (-110)
[ 1679.379609] usb 1-1: 1:1: usb_set_interface failed (-110)
```

Update: This is related to https://github.com/hathach/tinyusb/pull/1802 stuff (`assertion "hw_data_offset(next_buffer_ptr) <= USB_DPRAM_MAX" failed`). Applying PR https://github.com/hathach/tinyusb/pull/1802 fixes the `audacity` related crash 100%.

For testing convenience, I am attaching the built .uf2 file [here](https://github.com/hathach/tinyusb/files/11722810/cdc_uac2.uf2.txt).

CC @angmolin for visibility.

### CODE REVIEW

**Comment by mkarliner** [comment]
If you interested in making this a full project with board and case designs I'd be interested in joining.

**Comment by kholia** [comment]
> If you interested in making this a full project with board and case designs I'd be interested in joining.

One of the points of this work is to power various radio interfaces over a single USB cable without even touching the soldering iron (and those LQFP48 chips), if desired.

This being said, let's see what the future holds - thanks!

**Review by angmolin — APPROVED** [review]

**Comment by hathach** [comment]
thanks @kholia , I will review this as soon as I could.

**Review by hathach — APPROVED** [review]
superb! Thank you very much for your PR and patient. I was super busy with other works. I have pulled and tested, added makefile so that we could build with other mcus without the huge list of skip.txt. Also update descriptor to build with nrf52 and a couple of file renaming to reduce confusion as tud_cdc.c look like it comes from the stack. Overally it is great, I haven't tested it on other mcus though, but should work (else we could fix later).

**Pull request merged**
