### PR TITLE
add app driver as suggested by #467

### LINKED ISSUE #384: Allow overriding class drivers table
At the moment, is is only possible to define one custom device class driver through custom_device.h/.c. When tinyusb is used as part of a larger application or framework, it becomes inconvenient since the specific driver to be used might only be known at run time, not at compile time.

It would be great if `static usbd_class_driver_t const usbd_class_drivers[]` would be made overridable by the application, without having to modify TinyUSB source code.

There are a few ways to achieve this, here is a relatively simple modification which should not affect the existing apps. It involves 3 changes:

1. Define each standard class driver structure as a separate const variable, expose this variable in the public header file.
2. Compose the default array of class drivers from the pointers to the class driver structures.
3. Allow the array of class drivers to be overridden.

Here is how it can look like:

```c++
  /* Define each class driver as a separate structure */
  #if CFG_TUD_CDC
    usbd_class_driver_t const tusb_cdc_class_driver = 
    {
        .class_code      = TUSB_CLASS_CDC,
        .init            = cdcd_init,
        .open            = cdcd_open,
        .control_request = cdcd_control_request,
        .control_request_complete = cdcd_control_request_complete,
        .xfer_cb         = cdcd_xfer_cb,
        .sof             = NULL,
        .reset           = cdcd_reset
    },
  #endif

  /* Same for the rest of the default class drivers */

  /* The default drivers table. Note that these are pointers to usbd_class_driver_t */
  static usbd_class_driver_t const* usbd_class_drivers_default[] = {
  #if CFG_TUD_CDC
    tusb_cdc_class_driver,
  #endif
  /* The rest of the default class drivers */
  };

  const usbd_class_driver_t **usbd_class_drivers = usbd_class_drivers_default;
  size_t usbd_class_drivers_count = sizeof(usbd_class_drivers_default)/sizeof(usbd_class_driver_t*);
```

In some public header file, expose the class driver structures, and the `usbd_class_drivers` variable:

```c++
    usbd_class_driver_t const tusb_cdc_class_driver;
    /* the rest of the class driver structures */

   const usbd_class_driver_t **usbd_class_drivers usbd_class_drivers;
   size_t usbd_class_drivers_count;
```

With this, the application can define a custom list of class drivers:

```c++
const usbd_class_driver_t** my_class_drivers = {
  tusb_cdc_class_driver,
  my_class_driver_1,
  my_class_driver_2
};

usbd_class_drivers = my_class_drivers;
usbd_class_drivers_count = sizeof(my_class_drivers) / sizeof(my_class_drivers[0]);
```

Alternatively, instead of exposing the array + size, it can be required to make the array terminated by a NULL pointer.

Instead of exposing global `usbd_class_drivers` and `usbd_class_drivers_count`, it is possible to expose a setter function.

### LINKED ISSUE #467: Custom addition usbd driver
In _usbd_driver array (in file usbd.c), could add a include like
```c
#ifdef USBD_DRIVER_INCLUDE_H
#include USBD_DRIVER_INCLUDE_H
#endif

#ifdef USBD_DRIVER_INCLUDE
#include USBD_DRIVER_INCLUDE
#endif
```
to support user custom usbd drivers, avoiding modifying files.

The file will be like:
```c
#include "tusb.h"
#include "device/usbd.h"
#include "device/usbd_pvt.h"
#include "device/dcd.h"

#ifdef USBD_DRIVER_INCLUDE_H
#include USBD_DRIVER_INCLUDE_H
#endif

// ...

static usbd_class_driver_t const _usbd_driver[] =
{
// Original content
  #if CFG_TUD_CDC
  {
      DRIVER_NAME("CDC")
      .init             = cdcd_init,
      .reset            = cdcd_reset,
      .open             = cdcd_open,
      .control_request  = cdcd_control_request,
      .control_complete = cdcd_control_complete,
      .xfer_cb          = cdcd_xfer_cb,
      .sof              = NULL
  },
  #endif

// More ...

// Add this
#ifdef USBD_DRIVER_INCLUDE
#include USBD_DRIVER_INCLUDE
#endif

};

// ...
```

User can define USBD_DRIVER_INCLUDE, e.g. `<usbd_driver.include>`
The file `usbd_driver.include` content could be like:
```c
{
	DRIVER_NAME("CCID")
	.init = ccid_init,
	.reset = ccid_reset,
	.open = ccid_open,
	.control_request = ccid_control_request,
	.control_complete = ccid_control_complete,
	.xfer_cb = ccid_xfer_cb,
	.sof = NULL
},
// More ...
```

### PR DESCRIPTION
**Pull request by hathach**
**Describe the PR**
- Add app driver as suggested by #467, more preferable than #385 
- Fix #384 , Fix #467 

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

@igrr @me-no-dev

### CODE REVIEW

**Comment by me-no-dev** [comment]
We can definitely work with that 👍

**Comment by igrr** [comment]
@hathach Am I right that this approach, compared to #385, does not allow the list of drivers to be defined dynamically, and we still need to know the list of drivers at compile time?

This option is certainly better than not having any way to customize the driver list, so 👍 on that. However the callback option still seems to be preferable since it allows both compile-time defied list of custom drivers, or run-time defined list of custom drivers.

**Comment by HiFiPhile** [comment]
I think it's enough for most user cases.

**Comment by hathach** [comment]
> @hathach Am I right that this approach, compared to #385, does not allow the list of drivers to be defined dynamically, and we still need to know the list of drivers at compile time?
> 
> This option is certainly better than not having any way to customize the driver list, so  on that. However the callback option still seems to be preferable since it allows both compile-time defied list of custom drivers, or run-time defined list of custom drivers.

@igrr yeah, this approach is very static, much like current implementation. Which is why I really like it. Could you tell me in which scenario you need to have an run-time driver list. If it is lightly used, this approach can actually be implemented as run-time defined as well, application only need to
- define the all the driver it could possibly enable with the macro
- for driver that is disabled in run-time, just use an local variable to return 0/false upon called e.g `if (driver_disabled) return 0;` in open().

I know esp32 has a great heap management, but I still prefer to having everything static as much as possible within the stack. As always, I am open for any suggestion/discussion as well.

**Comment by me-no-dev** [comment]
@hathach I can try to give an example: 
- The ESP32 camera driver is a separate component that can benefit from having it's own webcam driver support that can be loaded if the component is in the project and enabled.
- ESP32-Arduino will also be able to load it's own custom drivers (or the above camera driver) independent of what is precompiled from ESP-IDF.

I am sure @igrr could fill in more cases :)

**Comment by igrr** [comment]
Yes, pretty much what @me-no-dev said — the main reason for dynamic registration is to not centralize the knowledge of all the custom drivers in one place.
Which is not easy from the build system perspective — how to allow 3rd party components to contribute entries to CFG_TUD_APP_DRIVER_HEADER?
As an example, we have a virtual filesystem (VFS) component in IDF, which allows dynamic registration of filesystem drivers. The filesystem driver can be provided in a third party component, and VFS layer doesn't need to know about the specific driver at compile time.

I think the callback approach is compatible both with compile-time driver registration (no heap allocation required), as well as run-time registration.

As to the approach you suggest with reserving some "slots" in the driver table, i think it can work as well, although it does feel a bit hacky compared to having a callback.

**Comment by hathach** [comment]
thanks @igrr , it is a valid point to support 3rd party drivers. IDF is much more comprehensive that what I have been done so far. I will get back to the #385 . Thanks for explanation.

**Pull request closed without merging**
