### PR TITLE
Example cdc uac2

### PR DESCRIPTION
**Pull request by angmolin**
The `cdc_uac` example has been added. This sample provides an audio interface combined with a serial port interface both working simultaneously.

### CODE REVIEW

**Comment by hathach** [comment]
thank you for your PR, unfortunately, I don't see added value for combine cdc with uac2 in an example. We can't have every example for each driver combination. User with cdc interest could test out other example

**Comment by kholia** [comment]
Hi @hathach - The CDC + UAC2 composite device happens to be important especially in the amateur radio community.

Modern radios ('rigs') like Icom IC-7300 + IC-705 expose a sound card and a serial device ('composite device') to the computer over a single USB cable. This allows for Audio I/O and CAT control over a single USB cable which is very convenient.

By including (and enhancing) the example in this PR, we enable the amateur radio community to build ('homebrew') radios with similar functionality as the expensive commercial rigs.

This PR is important in bridging this specific gap between the commercial rigs and homebrew equipment.

...

Another use case: https://digirig.net/digirig-mobile-rev-1-9/ is a digital interface for interfacing radios (that lack an inbuilt digital interface) with computers. Digirig Mobile works brilliantly (is OSS!) and is a big improvement over traditional digital interfaces (like the `SignaLink USB Interface`). By using a Raspberry Pi Pico powered CDC + UAC2 composite device, we can simplify the Digirig Mobile schematic, drastically reduce the manufacturing cost, and (again) enable the homebrewers community  to homebrew a modern digital interface with ease themselves.

Overall, this PR has quite a bit of unmatched potential - thanks for your time and attention in re-considering it.

Cheers,
Dhiru (VU3CER / KN6SDN)

Related: https://github.com/hathach/tinyusb/issues/1911.

**Comment by dhalbert** [comment]
@hathach I have one of the radios mentioned and understand the motivation.
@kholia I think it would be good to add a README or comment to explain the motivation, rather than have it be implicit. That would make it more findable by a search engine.

**Comment by dhalbert** [comment]
@kholia You could also make your own repo that is just the example, so that you can point to it, and write an extended README that would explain what this is for.

**Comment by hathach** [comment]
Re-opened thanks @kholia for explanation, I will re-evaluate this later on

**Comment by mkarliner** [comment]
I thought of same use case. Pi zeros have only one USB port.

**Comment by kholia** [comment]
I have opened https://github.com/hathach/tinyusb/pull/2105 now. All feedback is welcome - thanks!

**Pull request closed without merging**
