### PR TITLE
valentyusb: eptri: coalesce resets

### PR DESCRIPTION
**Pull request by xobs**
Sorry, found another small issue.  I was overflowing the queue with reset events.  This prevented it from working on Intel boards under Linux.

### CODE REVIEW

**Comment by xobs** [comment]
I think the issue might be considered a hardware bug.

For starters, the CPU can be incredibly slow, especially if it's executing out of XIP SPI flash.

Next, the `usb_reset` hardware signal basically indicates whether the device is _currently in reset_.  That is, that signal goes high when a reset starts, and goes low when a reset finishes. https://github.com/im-tomu/valentyusb/blob/master/valentyusb/usbcore/rx/pipeline.py#L48-L58

This signal is exposed to `eptri, and is directly wired into an `EventSourcePulse` as the trigger: https://github.com/im-tomu/valentyusb/blob/97ac21d6ea4f9b632773a833476906c1ab95a730/valentyusb/usbcore/cpu/eptri.py#L497

However, the way `EventSourcePulse` appears to be implemented, if the signal is long and not just a short pulse, it becomes a level-triggered interrupt instead of an edge-triggered one: https://github.com/enjoy-digital/litex/blob/master/litex/soc/interconnect/csr_eventmanager.py#L73

So perhaps this should be fixed in the hardware as well.

**Comment by hathach** [comment]
@xobs yeah, I think this counts as hw issue, it is much better if you could fix this issue in the core. The interrupt should only fired at the end of reset sequence. Although the specs say SE0 ~ 10ms is counted as reset. Host controller driver (windows/linux) normally can prolong it to typically 50-100 ms. Though the software walk-around is still enough for now, we can revert this back later on :)

image

**Comment by hathach** [comment]
Let's me know if you want me to merge the PR for now, or decide to fix the hardware instead :)

**Comment by xobs** [comment]
I think better to fix it in hardware, since the device is effectively unusable when the host has it in reset.  With this patch, tinyusb will no longer give asserts, it'll just stop working.

**Comment by hathach** [comment]
Let's fix the hardware then :)

**Comment by xobs** [comment]
Fixed in https://github.com/im-tomu/valentyusb/commit/b262b994fd9e6568b257b8424fe808cfc403e652

**Pull request closed without merging**
