### PR TITLE
support stm32U0 device

### PR DESCRIPTION
**Pull request by Maerdl**
Hello ,

i added the basic support for STM32U0 devices. As it uses the same usb core than the U5 series it's just some defines to add.
It was tested with a custom board as a cdc device. No further tests are done.

Are there any further needs to get merged into the main repo ?

Thanks in advance
Maerdl

### CODE REVIEW

**Review by hathach — APPROVED** [review]
look good, ci failed due to my HIL machine migration. Just merge latest and pushed. Hopefully this should fix it.

**Comment by HiFiPhile** [comment]
Thanks for your PR, I think U0 only use fsdev driver, you can revert the changes in `src/portable/synopsys/dwc2/dwc2_stm32.h`

**Review by hathach — CHANGES_REQUESTED** [review]
@HiFiPhile is right, I overlook this. U0 is fsdev only, please update PR accordingly.

image

**Review by hathach — APPROVED** [review]
the revert is simple, I made the update myself. There is a bit of duplication in fsdev driver, but we will clean that up later.

**Comment by Maerdl** [comment]
Thank's guys for the quick solution on that !

**Pull request merged**
