### PR TITLE
Add CH32V20x USB OTG/FS Driver

### PR DESCRIPTION
**Pull request by dragonlock2**
**Describe the PR**
Added support for the USB OTG/FS driver found in the CH32V20x microcontrollers, heavily inspired by the CH32V307 driver. While not tested, this driver should also work for the matching IP in the CH32V307.

Note there is an older incomplete PR https://github.com/hathach/tinyusb/pull/1995 that was trying to accomplish something similar.

**Additional context**
Driver does appear to be working well, I'm currently using it to implement a basic RPC using bulk transfers and 8-channel 16-bit 48kHz audio streaming in [dragonlock2/miscboards/wch/rvice_adc](https://github.com/dragonlock2/miscboards/tree/main/wch/rvice_adc).

### CODE REVIEW

**Review by hathach — COMMENTED** [review]
sorry still haven't got time to test this out. I am off for TET holidays for a couple of weeks. Will try to review afterwards, thank you for your patient.

**Comment by mean00** [comment]
I did a quick test  with CH32V30X chips, it seems to work also there (very minor changes needed because i'm not using wch SDK)
Good job!

**Comment by greenscreenflicker** [comment]
I'm just trying to compile the Pull request. I'm documenting here my process.

1. I'm getting an error in dcd_int_handler(uint8_t rhport) . That a semicolon is missing after a declaration.
         switch (token) {
            case PID_OUT:**;**
                uint16_t rx_len = USBOTG_FS->RX_LEN;
                update_out(rhport, ep, rx_len);
                break;

**Comment by dragonlock2** [comment]
> I'm just trying to compile the Pull request. I'm documenting here my process.
> 
> 1. I'm getting an error in dcd_int_handler(uint8_t rhport) . That a semicolon is missing after a declaration.
>    switch (token) {
>    case PID_OUT:**;**
>    uint16_t rx_len = USBOTG_FS->RX_LEN;
>    update_out(rhport, ep, rx_len);
>    break;

**Comment by greenscreenflicker** [comment]
I would apprechiate here a warning in compile time, not in runtime...
```
 void board_init(void) {
    __disable_irq();

#if CFG_TUSB_OS == OPT_OS_NONE
    SysTick_Config(SystemCoreClock / 1000);
#endif


    switch (SystemCoreClock) {
        case 48000000:  RCC_USBCLKConfig(RCC_USBCLKSource_PLLCLK_Div1); break;
        case 96000000:  RCC_USBCLKConfig(RCC_USBCLKSource_PLLCLK_Div2); break;
        case 144000000: RCC_USBCLKConfig(RCC_USBCLKSource_PLLCLK_Div3); break;
        default: TU_ASSERT(0,); break;
    }
```

**Comment by greenscreenflicker** [comment]
> > I'm just trying to compile the Pull request. I'm documenting here my process.
> > 
> > 1. I'm getting an error in dcd_int_handler(uint8_t rhport) . That a semicolon is missing after a declaration.
> >    switch (token) {
> >    case PID_OUT:**;**
> >    uint16_t rx_len = USBOTG_FS->RX_LEN;
> >    update_out(rhport, ep, rx_len);
> >    break;
> 
> Some compilers don't like declaring a variable inside a switch/case. Added brackets to fix.

Fixed by additional semicolon... see PID_OUT... Thanks for the support so far!

**Comment by greenscreenflicker** [comment]
@dragonlock2 does it support CDC also?

**Comment by dragonlock2** [comment]
I prefer brackets for readability, didn't know a semicolon also works. The driver supports all of the transfer types needed in USB, so this should work for CDC too.

**Comment by greenscreenflicker** [comment]
Can you please give me some hints why I don't get enumeration. What could I do wrong?
I run it in Freertos, in a seperate task. It looks like this:

```
void task1_task(void *pvParameters)
{

    board_init();

    // init device stack on configured roothub port
    tud_init(BOARD_TUD_RHPORT);

    if (board_init_after_tusb) {
      board_init_after_tusb();
    }

    while (1) {
      tud_task(); // tinyusb device task
      tud_cdc_n_write_str(0,"Hello, World!\r\n");
      vTaskDelay(10);
    }
}
```

**Comment by dragonlock2** [comment]
@greenscreenflicker let's continue this part of the discussion on https://github.com/hathach/tinyusb/discussions/2525 and keep comments here focused on the PR

**Comment by greenscreenflicker** [comment]
Please mention in the files, that it only works with some of the devices, having the right module. (H/D in the grafics below)

grafik

**Comment by dragonlock2** [comment]
Not sure what @hathach would prefer, but I think the driver names are enough documentation. `dcd_ch32_usbfs.c` is for the USBFS/OTG_FS IP and `dcd_ch32_usbhs.c` is for the USBHD IP.

Notably some CH32V20x only have the USBD IP which I believe may be compatible with the STM32 driver.

**Comment by ddB0515** [comment]
I would be very interested into this as have 2 boards with v203(CH32V203G6U6 and CH32V203C8U6)
If you need any test let me know but love to have normal USB access with tinyUSB

**Comment by greenscreenflicker** [comment]
@ddB0515 Note that CH32V203G6U6 is not supported, while CH32V203C8U6 probbably is.
The naming by wch (@openwch) of the devices in unfortunate.

**Comment by ddB0515** [comment]
@greenscreenflicker will CH32V203G6U6 work at least as HID/CDC? as that is supported as USB Device or I'm wrong?

**Comment by greenscreenflicker** [comment]
@ddB0515 CH32V203G6U6 doesn't work with CDC/HID. I use that MCU also, and have the problem.  See here: 
https://github.com/hathach/tinyusb/discussions/2525#discussioncomment-8912923

**Comment by dragonlock2** [comment]
@ddB0515 @greenscreenflicker as I expected the existing dcd_stm32_fsdev.c works for the USBD of CH32V20x. See [dragonlock2/miscboards/wch/mouse_jiggler](https://github.com/dragonlock2/miscboards/tree/main/wch/mouse_jiggler). Let's continue discussion on https://github.com/hathach/tinyusb/discussions/2525 and keep this PR focused on the USB OTG/FS driver.

**Comment by hathach** [comment]
thank you for your PR. I am testing this out, rebased (with latest) and also fix ci build and other minor change to cmake build https://github.com/hathach/tinyusb/tree/pr2362_rebased , but I couldn push to this PR since you haven't allow maintainner to update this. Would you mind changing the PR to give me the write permission.

**Comment by dragonlock2** [comment]
try it now, you should be able to push to my fork

**Comment by hathach** [comment]
> try it now, you should be able to push to my fork

Thank you, I have push the rebased to your fork. Though it isnt quite working, it keep stalling the get configuration. (stall is set with device qualifier previous, should be clear on setup). I may be due to recent chagnes on master, though it shows that this driver is partially working. I am doing more test and try to fix it if I could.

image

**Comment by dragonlock2** [comment]
Interesting, it's still working well on my end with my [mouse_jiggler](https://github.com/dragonlock2/miscboards/tree/main/wch/mouse_jiggler) example. I do build things differently, but I wouldn't imagine it makes a big difference. I've run into issues before where if `bcdUSB` is set to `0x0200` instead of `0x0110`, a descriptor is requested that gets stalled and device doesn't enumerate.

I can take a look too, which example are you running?

**Comment by hathach** [comment]
I am testing with cdc_msc stock example. yeah, setting bcdUSB to 2.0 with fullspeed will cause host to request device qualifier --> which tinyusb will stall as an not supported. I think the current driver didn't clear stall correctly. I will revise the driver and fix that later, I think we are getting closed to merge this. I will also cross-checking/cherry-pick with code in  #1995 as well.

**Comment by dragonlock2** [comment]
Try it now, I didn't realize `dcd_edpt_xfer` should clear the stall, added a call to `dcd_edpt_clear_stall`. Looks like it's enumerating now on my end with `bcdUSB` set to `0x0200`.

**Comment by hathach** [comment]
@dragonlock2 no, it is not correct behavior. We should only clear EP0 stalled status (both in and out) when receiving SETUP token. For non-control endpoint, the stalled status remain until it is explicitly cleared by host.

**Comment by dragonlock2** [comment]
I see, I just moved the `dcd_edpt_clear_stall` calls to the interrupt when the setup token is received

**Comment by hathach** [comment]
> I see, I just moved the `dcd_edpt_clear_stall` calls to the interrupt when the setup token is received

perfect, I am about to pus the update, but you are faster than me. It is enumerated now, it is now safe to do some "minor" moving and/or generalizing the driver. Will try to merge this soon enough.

**Review by hathach — APPROVED** [review]
Thank you very much for your effort and patient. This works perfectly well with both my v203 and v307 dev board. I have update the linker for v20x to support different flash/ram size (by symdef __flash/ram_size), which should work better for more boards than default 64k/20k.

I also change the usbhs and usbfs driver a bit so that it is used correctly with CFG_TUD_MAX_SPEED since high-end ch32 such as v307 support both controller. 

Note: v203 also support both usbfs and stm32 fsdev, but that selection will be added later as follow up PR.

This should also close #1995

**Comment by Devin-goBILDA** [comment]
@dragonlock2 I am attempting to use the CH32V203 with the DFU device class, for some reason I am running into an issue that is causing a PMAOVR interrupt. I don't have much low level knowledge of USB. If you are willing and have some time I would appreciate it if you could take at look at this issue: https://github.com/hathach/tinyusb/issues/3573

**Pull request merged**
