### PR TITLE
Modified example to use list of supported boards

### PR DESCRIPTION
**Pull request by PTS93**
There is now a seperate file to maintain all supported boards.
Maybe Adafruit can generate this for their line of boards?

### CODE REVIEW

**Comment by hathach** [comment]
superb! thanks, I could fill out the board later. Don't worry too much about it, btw can we take the vid/pid from command line e.g `node hid_test.js -d 239a:1234`  just in case other vendor want to try it out as well, and we cannot keep the list up to date in time.

PS: I still prefer to have only one hid_test.js, but it is ok to have 2 :)

**Comment by PTS93** [comment]
I thought it might make sense to keep that seperated to not end up with a 600 line example at some point :)
If someone want to test their own vid pid pair it would make sense they just add that to the list I would say, they don't have to push the change if they just want to test something.

**Comment by PTS93** [comment]
we could make it a json file instead, then other applications could also read it, like python

**Comment by hathach** [comment]
Make all the sense, thanks for the pr :)

**Pull request merged**
