### PR TITLE
RP2040 MIDI host

### PR DESCRIPTION
**Pull request by atoktoto**
**Describe the PR**
This PR adds MIDI host support for RP2040 boards based on work done by @rppicomidi in https://github.com/hathach/tinyusb/pull/1219 and @Skyler84 in https://github.com/hathach/tinyusb/pull/1434. I rebased all changed on top of master and fixed some compilation errors. 

MIDI controller (behringer x-touch mini) enumerates and the data is received. 

Creating this pull request as a draft for comments. I'm very new at this and I'm kind of surprised that it works :D

### CODE REVIEW

**Comment by atoktoto** [comment]
Not sure if that's the source of the problem but the way I have it set up is the same as described by the original author of this merge request: https://github.com/rppicomidi/midi2usbhost ( "Using the forked tinyusb library" )

**Comment by atoktoto** [comment]
Here is a stripped down example project created from the example: https://github.com/atoktoto/pico-midi-host

**Comment by rppicomidi** [comment]
@atoktoto  In case you are interested, my fork of this project has a new branch pio-midihost that supports the Pico-PIO-USB as a host. I have a demo project pico-usb-midi-filter that passes MIDI data between the built-in USB configured as a device and a new USB Host port created from PIO. I suspect I duplicated some of your work in this pull request in my fork.

**Comment by atoktoto** [comment]
@rppicomidi Is the Pico-PIO-USB a way to go over the dedicated hardware? Why?

**Comment by rppicomidi** [comment]
@atoktoto I agree #1434 seems to work. I am not arguing against your pull request. Thank you for doing the work. The [pico-usb-midi-filter](https://github.com/rppicomidi/pico-usb-midi-filter) project uses a single Pico board to implement a bi-directional MIDI filter between a MIDI USB host (which I implemented using PIO from the Pico-PIO-USB project) and a MIDI USB device (which I implemented using the Pico's dedicated USB hardware). My comment was only wishing I had looked here before I did a lot of the same work you did.

**Pull request closed without merging**
