### PR TITLE
Fix edpt_close() of stm32_fsdev

### LINKED ISSUE #1693: Closing endpoint fails for stm32_fsdev
### Operating System

MacOS

### Board

BluePill STM32F103C8

### Firmware

Custom firmware at https://github.com/manuelbl/JavaDoesUSB/tree/main/test-devices/loopback-stm32.

Build instructions are in the README. It's a PlatformIO project.

The code contains a copy of the relevant tinyusb parts including a fix for this issue.

### What happened ?

When `usbd_edpt_close()` is called, the firmware crashes at https://github.com/hathach/tinyusb/blob/master/src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c#L742:

```
TU_ASSERT(open_ep_count > 2, /**/);
```

This isn't surprising as there is no code that increases the value of `open_ep_count`. It is unlikely it has ever worked.

### How to reproduce ?

- Build the firmware with original version of *dcd_stm32_fsdev.c*
- Connect the BluePill board with an ST-Link adapter and start the debugger (from PlatformIO)
- Open the Java project at https://github.com/manuelbl/JavaDoesUSB/tree/main/java-does-usb (requires Java 19)
- Run the unit tests

The debugger will stop at the above mentioned line.

### Debug Log as txt file

_No response_

### Screenshots

_No response_

### I have checked existing issues, dicussion and documentation

- [X] I confirm I have checked existing issues, dicussion and documentation.

### PR DESCRIPTION
**Pull request by manuelbl**
**Describe the PR**
This is a fix for bug #1693, which prevented the use of `usbd_edpt_close()` for *stm32_fsdev*.

**Additional context**
Fixes #1693

This fix is needed for a custom vendor driver, supporting alternate interfaces. See https://github.com/manuelbl/JavaDoesUSB/tree/main/test-devices/loopback-stm32.

### CODE REVIEW

**Comment by manuelbl** [comment]
One of the builds has failed. But not due to my code changes. Rather it's an internal compiler error triggered by completely unrelated code (see below). This is not the only affected PR. I can see at least 3 more affected ones. And they don't all fail on the same code. It also affects the RP2040.

Are you aware of the issue? How should we proceed with this?

```
/home/runner/work/tinyusb/tinyusb/hw/mcu/nuvoton/nuc505/StdDriver/src/clk.c:26:5: internal compiler error: Illegal instruction
   26 |     { 1, 1, 50.0, },
      |     ^

...

0x1521b50 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
	???:0
0x15227d6 internal_error(char const*, ...)
	???:0
0xb7838f crash_signal(int)
	???:0
0x171b592 __gmpn_mul_basecase
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
make: *** [../../rules.mk:130: _build/nutiny_sdk_nuc505/obj/hw/mcu/nuvoton/nuc505/StdDriver/src/clk.o] Error 1
```

```
/home/runner/work/tinyusb/tinyusb/hw/bsp/sltb009a/sltb009a.c: In function 'emu_reg_init':
/home/runner/work/tinyusb/tinyusb/hw/bsp/sltb009a/sltb009a.c:101:5: internal compiler error: Illegal instruction
  101 |     if(target_voltage < 2300.f || target_voltage >= 3800.f)
      |     ^~


...

0x1521b50 diagnostic_impl(rich_location*, diagnostic_metadata const*, int, char const*, __va_list_tag (*) [1], diagnostic_t)
	???:0
0x15227d6 internal_error(char const*, ...)
	???:0
0xb7838f crash_signal(int)
	???:0
0x171b592 __gmpn_mul_basecase
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
make: *** [../../rules.mk:131: _build/sltb009a/obj/hw/bsp/sltb009a/sltb009a.o] Error 1
```

**Comment by hathach** [comment]
this PR is not needed, since fsdev now reserve max packet for ISO transfer

**Comment by manuelbl** [comment]
I had fixed `usbd_edpt_close()` because it was needed to implement switching between alternate interfaces. Is this now possible without this fix?

**Comment by HiFiPhile** [comment]
> I had fixed `usbd_edpt_close()` because it was needed to implement switching between alternate interfaces. Is this now possible without this fix?

Yes, you can try UAC headset example.

**Pull request closed without merging**
