### PR TITLE
RP2040 tweaks

### PR DESCRIPTION
**Pull request by liamfraser**
RP2040 tweaks:
- Compiler warning fixes
- allow pico-sdk LWIP to be used if TinyUSB one does not exist
- Use custom memcpy in RP2040 code
- Don't clear registers when not needed as hardware reset already does it

### CODE REVIEW

**Review by hathach — APPROVED** [review]
look good, thank you

**Comment by earlephilhower** [comment]
I know this has been merged, but replacing memcpy with a [local implementation](https://github.com/hathach/tinyusb/commit/770efd9b46db0f8723beebe4bfa4d6694bac2901) makes no sense to me.

`memcpy`, by definition, does not have any alignment restrictions (but of course you need `memmove` if there's potential overlap).  I would suggests that any `memcpy` that crashes on a non-4-byte-aligned input or output is busted or should not be called `memcpy` because lots of other things are going to break, not just USB.

None of the `man` pages (ISO C spec is $$$) I've [seen](https://pubs.opengroup.org/onlinepubs/007904975/functions/memcpy.html) [show](https://man7.org/linux/man-pages/man3/memcpy.3.html) [an](https://en.cppreference.com/w/c/string/byte/memcpy) alignment requirement.  

While the implementation here of `unaligned_memcpy` looks like it works (but doesn't return the almost always unused pointer that ISO `memcpy` does), it feels like it's going to be slower than whatever GCC or the ROM would implement...

**Comment by hathach** [comment]
@earlephilhower yeah, thank you for your feedback. You are rigtht, this is my thought as well initially. However, since it copy to/from a dual port USB RAM, it may have some extra hw limit, we have seen this in other ports e.g https://github.com/hathach/tinyusb/pull/1024, though that is a bit different since MCU is M4 and able to do unaligned access (hence memcpy is implemented in such as way), however the usb ram is limited to byte/aligned access only which could cause issue.

For this PR, M0 may not make sense, but, maybe RPI team want to fix something in advance. For now I would like have @liamfraser to confirm that if this unaliged function is tested for fixing actual issue or just simply an prevention ?

**Comment by earlephilhower** [comment]
Gotcha.  Thanks to all for looking into it.

**Comment by hathach** [comment]
> Gotcha. Thanks to all for looking into it.

no problems, thank you for providing feedback on the PR.

**Pull request merged**
