### PR TITLE
add mm32 bsp

### PR DESCRIPTION
**Pull request by zhangslice**
**Describe the PR**
A clear and concise description of what this PR solve.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

### CODE REVIEW

**Comment by hathach** [comment]
Thanks for the PR to add BSP for your board. Though the dcd is already added at location https://github.com/hathach/tinyusb/tree/master/src/portable/mindmotion/mm32 . I moved it into the `src/portable/mindmotion/mm32` folder. To help pushing this PR, I will push the update myself.

**Comment by hathach** [comment]
I have added makefile (family.mk and board.mk) to allow building the mb39 board, though It needs https://github.com/zhangslice/mm32sdk/pull/1 to be merged first to add the startup file for gcc. 

@zhangslice I couldn't find a way to flash the board to test its functionality. My windows VM couldn't able to connect to the mcu using mm32-link. The led next to the link usb connection blinking forever. Any tips to connect and flash the board would be helpful.

image

**Comment by zhangslice** [comment]
The.ld file is added in DSP, and the.s file is in my branch. All products with ARM kernel can use JLink. The on-board debugger we brought with us also provides a JLink socket. I have sent you the schematic diagram of the board for you to check, and it is marked accordingly. You don't need to use our own upper computer software. If you want to use it, you need to install the driver and there are instructions on the official website.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hathach/tinyusb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hathach/tinyusb] add mm32 bsp (#897)





 
I have added makefile (family.mk and board.mk) to allow building the mb39 board, though It needs zhangslice/mm32sdk#1 to be merged first to add the startup file for gcc.
 
@zhangslice I couldn't find a way to flash the board to test its functionality. My windows VM couldn't able to connect to the mcu using mm32-link. The led next to the link usb connection blinking forever. Any tips to connect and flash the board would be helpful.

**Comment by hathach** [comment]
@zhangslice I don't see the startup file (.S) for gcc in your PR. There is also other typo (incorrect file name which will failed to compile on case-sensitive OS like Linux). Can you check out the PR and merge it to your sdk https://github.com/zhangslice/mm32sdk/pull/1

For using Jlink, I also like to use it as well, however, the supported list from jlink does not cover your MM32F327 yet https://www.segger.com/downloads/supported-devices.php?m=MindMotion , which device should I use to flash the board ?

**Comment by hathach** [comment]
superseded by #1117

**Pull request closed without merging**
