### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by perigoso**
Rework of the documentation

This unifies all the current information about the project in an online documentation page, this will be hosted on readthedocs.
This PR adds very little NEW information, but it builds a good foundation where further documentation can be built uppon.

To simplify the visualization of the PR the new docs can be preview here https://perigoso.github.io/tusb_docs_showcase/

Some docs need some priority work, like the new supported devices table, because i am not familiar with all the supported families i was unable to properly populate the table (read: hackjob)

#966

### CODE REVIEW

**Comment by perigoso** [comment]
TODO: 
we need to setup the readthedocs project, this can be done right after the merge by someone with admin rights.

we also need to setup the domain, an ANAME or ALIAS needs to be setup to point to the readthedocs page once its up.

**Comment by hathach** [comment]
superb !! Thank you very much for the hard work, it looks fabulously. There is only 2 minor issues
1. I still want to keep most of the project information as part of the readme since that is where most github user will look at. I rather to present it right away than require an extra click to external doc page. We can rename it to readme.rst like contributors.rst
2. The logo font doesn't look right, I would prefer to keep using the current logo. Do it need to be svg, I could try to export current design to that format. 

> TODO:
> we need to setup the readthedocs project, this can be done right after the merge by someone with admin rights.
> 
> we also need to setup the domain, an ANAME or ALIAS needs to be setup to point to the readthedocs page once its up.
> 
> the page should end up being in:
> https://tinyusb.readthedocs.io/

No problem, I could do this when this is merged.

**Comment by perigoso** [comment]
Hm, I understand, the problem with that is that you end up with 2 places with the same information that you need to make sure is updated at the same time.
Maybe we could link the internal files used in the docs in the readme, it should be readable on github since it's just rst, the user still has to click but doesn't need to go outside github, it's a good compromise?

I can do the logo myself, do you know the name of the font? If not I can trace manually. SVG is vector graphics so you can't export from the original.

**Comment by hathach** [comment]
> Hm, I understand, the problem with that is that you end up with 2 places with the same information that you need to make sure is updated at the same time.
> Maybe we could link the internal files used in the docs in the readme, it should be readable on github since it's just rst, the user still has to click but doesn't need to go outside github, it's a good compromise?

readme.rst should be displayed as readme.md on github if I am not mistaken e.g https://github.com/adafruit/circuitpython

> I can do the logo myself, do you know the name of the font? If not I can trace manually. SVG is vector graphics so you can't export from the original.

That is ok, don't worry about it. I will find way to export it. You have done more than enough.

**Comment by hathach** [comment]
here is the svg file,that I manage to create/export after quick google for how-to, please try to put that to the doc, I hope that is good enough [tinyUSB_logo_svg.zip](https://github.com/hathach/tinyusb/files/6905275/tinyUSB_logo_svg.zip)

**Comment by perigoso** [comment]
I have rebased with the logo you provided, I also added local links in the readme to all of the documentation, it's not perfect, but it's good enough for a quick glance at the documention without leaving github.

```
notice:
I have brought down the documentation repo
```

**Comment by perigoso** [comment]
You can merge if there's no changes you want made.

**Comment by perigoso** [comment]
Rebased on master, try not to merge anything that changes any of the docs before the merge

**Comment by HiFiPhile** [comment]
@perigoso I added myself in CONTRIBUTORS.rst :) If you need make changes pls do a pull.

**Comment by perigoso** [comment]
ah, no worries

**Comment by hathach** [comment]
@perigoso thank you very much for the update. This is a great update so far, I couldn't pull it off myself. However, in addition to dedicated documentation site, I still think the github readme.rst is one of the most important doc and should present the complete overview of the project like it does before. I wouldn't mind if there is duplication at this stage, we will try to enhance the rst doc later on (I still have to learn how to write doc for API anyway) and reduce the duplication later on. I made an PR to your docs branch here https://github.com/perigoso/tinyusb/pull/1 please check it out to see if that makes sense to you.

**Comment by perigoso** [comment]
That is fine, i understand. merged.

**Comment by hathach** [comment]
@perigoso thanks for updating, though please revert the re-org change, since I like the original one more.

**Comment by perigoso** [comment]
done.

**Review by hathach — APPROVED** [review]
Thank you very much @perigoso, this is a huge thing in my todo list. And I surely wouldn't pull it off without your help. This PR will make future updating document much easier than ever. There is still no API docs yet, but we will slowly but surely fill it up later on.

**Pull request merged**
