### PR TITLE
SAMx7x improvements

### PR DESCRIPTION
**Pull request by HiFiPhile**
**Describe the PR**
SAMx7x improvements.

- Add cache clean/invalidate.
- Move clock enable to BSP.

### CODE REVIEW

**Comment by HiFiPhile** [comment]
@fjgpereira @perigoso 
I've refactored register defines into a separate header, now it should be compatible with both frameworks and it makes porting easier.

I moved USB clock enable into BSP so you need to add
```
  // Enable USB clock
  PMC->PMC_PCER1 = 1 << (ID_USBHS - 32);
```

**Comment by hathach** [comment]
I checked out and tried with the PR but got into lots of USB issue, and cdc_msc doesn't mounted. Same setup work with existing master though. The symptom is pretty similar when using with long usb cable: enumeration complete but further transfer got stuck, I think it is due to PHY/bus unstable, it is probably already existed in master, but pr just make the timing (race condition) right to amplify the issue.

**Comment by HiFiPhile** [comment]
> I checked out and tried with the PR but got into lots of USB issue, and cdc_msc doesn't mounted. 

Hum... That's interesting.... I'm a little out of idea.  

@perigoso Could you make a test if your board ready ?

**Comment by perigoso** [comment]
board is ready, just need to setup the board support, I'll see If i have some time tomorrow

**Comment by hathach** [comment]
> > I checked out and tried with the PR but got into lots of USB issue, and cdc_msc doesn't mounted.
> 
> [a698dda](https://github.com/hathach/tinyusb/commit/a698dda67ef9980a0b8eaf0ab9d3edc9adf1c2f4) fixed speed detection, maybe it's the problem.
> 
> Otherwise I'm a little out of idea...
> 
> I've tried self/bus powered, low/high optimization, with/without RTT logging...
> 
> @perigoso Could you make a test if your board ready ?

Perfect, this fixed the issue with my set up, work great now

**Review by hathach — APPROVED** [review]
Supreb! Thank you @HiFiPhile for putting more effort to improve this port. This will allow adding more port using same controller easier in the future. :tada: :tada:

**Comment by perigoso** [comment]
Eh, Tried to test but the microchip submodule is still missing cmsis for the sam S 70, so i didnt bother

**Pull request merged**
