### PR TITLE
Add a HCD driver for MSP-EXP432E401Y

### PR DESCRIPTION
**Pull request by kkitayam**
**Describe the PR**
Add a HCD driver for [MSP-EXP432E401Y](https://www.ti.com/tool/MSP-EXP432E401Y).

This patch supports only for low and full speed devices.

**Additional context**
I have tested `cdc_msc_hid` with only a low speed mouse and `hid_controller` with a PS4 DS2 game pad.

### CODE REVIEW

**Comment by hathach** [comment]
another great port, thank you very much, please give me a bit of time to test this out.

**Comment by kkitayam** [comment]
I have found an issue with the handling of the HUB. I will let you know the issue is fixed.

**Comment by hathach** [comment]
> I have found an issue with the handling of the HUB. I will let you know the issue is fixed.

You could skip the hub port for now if that is too troublesome. I have my own temp code to handle hub as well like blocking delay and some hack here and there within enumeration code.

**Comment by kkitayam** [comment]
I have updated this patch for handling a HUB. However, the enumeration process with a HUB still fails.
I guess some race condition occur on a control transfer. Current `hcd_musb.c` assumes that a new transaction will not be requested(calling `hcd_setup_send`/`hcd_edpt_xfer`) until the previous transaction has been completed in a control transfer. However, it does appear to be requested.

I'm not familiar with USB host processing and EHCI/OHCI. It seems that `ehci.c` and `ohci.c` has a something like as a link list for queueing transaction requests. I guess that the queue enables speculative requests.

**Comment by hathach** [comment]
@kkitayam yeah, the enumeration via hub is still work in progress. No worries at all if it doesn't work out especially the usbh control flow isn't final just yet. We could come back to this later on.

**Comment by kkitayam** [comment]
@hathach
Thank you for your comment.
I will stop investigating the issue regarding enumeration with HUB for now.

In addition I have confirmed `hid_controller` works with my PS4 DS2 gamepad. So far, I confirmed interrupt IN transfers only work properly. This weekend I'm going to run bulk transfers.

**Comment by kkitayam** [comment]
I have confirmed bulk transfers work by connecting `cdc_msc_hid` to `msc_dual_lun` running on a raspberry pi pico.

**Review by hathach — APPROVED** [review]
superb! thank you very much for another great PR. The changes look perfect, I have tried to test it with tm4c123 board, however that board seems to need an a bit of extra works to set up as host mode (will implement later as separate PR). 

PS: I did push some minor changes to get host example build msp432e4 in ci and other minor changes.

**Comment by hathach** [comment]
> I have confirmed bulk transfers work by connecting `cdc_msc_hid` to `msc_dual_lun` running on a raspberry pi pico.

The msc example isn't good yet, previously I have an running example that could do some basic file navigation with fatfs such as `mkdir, cd, list, cat` but it is out of date with latest fatfs. I will try to get it updated to have an more fancy msc host example :)

**Comment by kkitayam** [comment]
Thank you for your comment and for merging this PR!

**Comment by hathach** [comment]
> Thank you for your comment and for merging this PR!

I am the one to say thanks :+1: :+1:

**Pull request merged**
