### PR TITLE
Add stm32f411disco board

### PR DESCRIPTION
**Pull request by hathach**
This PR add support for stm32f411e discovery board. Due to the limited number of endpoints of stm32f4 (up to 3 endpoints) on FS OTG core, the cdc_msc_hid exmaple must disable an class (e.g HID)
`CFG_TUD_HID = 0 in tusb_config.h` to work with. Other example such as msc_dual, midi_test should work without any issues.

@hierophect @dhalbert @tannewt @ladyada

### CODE REVIEW

**Comment by ladyada** [comment]
@hierophect please try this and we'll merge if it works for you!

**Comment by tannewt** [comment]
@ladyada looks like these changes only impact the example and the bsp which circuitpython doesn't use. It'd be good to get these going still to demonstrate the usb stack does work on the given board.

**Comment by ladyada** [comment]
@tannewt yup agree! @hierophect please try this to see if you can get USB enumeration & let us know

**Comment by hierophect** [comment]
I'm getting a number of errors in usb_control.c
```
In file included from ../../lib/tinyusb/src/tusb_option.h:70:0,
                 from ../../lib/tinyusb/src/device/usbd_control.c:27:
../../supervisor/shared/usb/tusb_config.h:110:50: error: expected declaration specifiers or '...' before numeric constant
 #define CFG_TUSB_MEM_ALIGN          ATTR_ALIGNED(4)
                                                  ^
../../lib/tinyusb/src/device/usbd_control.c:54:22: note: in expansion of macro CFG_TUSB_MEM_ALIGN'
 CFG_TUSB_MEM_SECTION CFG_TUSB_MEM_ALIGN uint8_t _usbd_ctrl_buf[CFG_TUD_ENDOINT0_SIZE];
                      ^~~~~~~~~~~~~~~~~~
../../lib/tinyusb/src/device/usbd_control.c: In function 'start_control_data_xact':
../../lib/tinyusb/src/device/usbd_control.c:78:12: error: '_usbd_ctrl_buf' undeclared (first use in this function); did you mean 'usbd_edpt_busy'?
     memcpy(_usbd_ctrl_buf, _control_state.buffer, xact_len);
            ^~~~~~~~~~~~~~
            usbd_edpt_busy
../../lib/tinyusb/src/device/usbd_control.c:78:12: note: each undeclared identifier is reported only once for each function it appears in
../../lib/tinyusb/src/device/usbd_control.c: In function 'usbd_control_xfer_cb':
../../lib/tinyusb/src/device/usbd_control.c:121:35: error: '_usbd_ctrl_buf' undeclared (first use in this function); did you mean 'usbd_edpt_busy'?
     memcpy(_control_state.buffer, _usbd_ctrl_buf, xferred_bytes);
                                   ^~~~~~~~~~~~~~
                                   usbd_edpt_busy
../../lib/tinyusb/src/device/usbd_control.c: In function 'start_control_data_xact':
../../lib/tinyusb/src/device/usbd_control.c:82:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [build-DIS_F411RE/lib/tinyusb/src/device/usbd_control.o] Error 1
```

I also noticed these in my PR attempt - I had to revert to an old commit to get rid of them.

**Comment by hierophect** [comment]
Note that the above only seems to apply to circuitpython itself... your example compiles fine. I'll look into it further.

**Pull request merged**
